INSERT INTO `directory_country_region_name` VALUES ('es_ES', 130, 'A Coruña');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 131, 'Alava');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 132, 'Albacete');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 133, 'Alicante');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 134, 'Almeria');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 135, 'Asturias');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 136, 'Avila');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 137, 'Badajoz');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 138, 'Baleares');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 139, 'Barcelona');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 140, 'Burgos');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 141, 'Caceres');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 142, 'Cadiz');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 143, 'Cantabria');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 144, 'Castellon');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 145, 'Ceuta');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 146, 'Ciudad Real');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 147, 'Cordoba');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 148, 'Cuenca');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 149, 'Girona');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 150, 'Granada');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 151, 'Guadalajara');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 152, 'Guipuzcoa');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 153, 'Huelva');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 154, 'Huesca');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 155, 'Jaen');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 156, 'La Rioja');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 157, 'Las Palmas');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 158, 'Leon');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 159, 'Lleida');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 160, 'Lugo');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 161, 'Madrid');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 162, 'Malaga');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 163, 'Melilla');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 164, 'Murcia');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 165, 'Navarra');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 166, 'Ourense');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 167, 'Palencia');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 168, 'Pontevedra');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 169, 'Salamanca');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 170, 'Santa Cruz de Tenerife');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 171, 'Segovia');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 172, 'Sevilla');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 173, 'Soria');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 174, 'Tarragona');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 175, 'Teruel');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 176, 'Toledo');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 177, 'Valencia');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 178, 'Valladolid');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 179, 'Vizcaya');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 180, 'Zamora');
INSERT INTO `directory_country_region_name` VALUES ('es_ES', 181, 'Zaragoza');
